version: "2.0"

services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:80"
    volumes:
      - drupal-html:/var/www/html
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgresspassword
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  drupal-html:
  psql-data:
